# Generated by Django 3.1.7 on 2021-04-01 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20210331_2240'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='disccount_percentage',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='sales',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
